# run the following loop and feed it to llm to get city country mapping
# for i in spark.sql("""select distinct(city) from all_matches""").collect():
#     print(i[0])
# give the country names for the following cricket test hosting cities in python dict format
test_hosting_cities = {
    "Worcester": "England",
    "Multan": "Pakistan",
    "Gaborone": "Botswana",
    "King City": "Canada",
    "Brighton": "England",
    "Prague": "Czech Republic",
    "Guacima": "Costa Rica",
    "Taunton": "England",
    "Chesterfield": "England",
    "Manchester": "England",
    "Scarborough": "England",
    "Bready": "Northern Ireland",
    "Cambridge": "England",
    "Cheltenham": "England",
    "Belfast": "Northern Ireland",
    "Lucknow": "India",
    "Chennai": "India",
    "Dar-es-Salaam": "Tanzania",
    "Cardiff": "Wales",
    "Harare": "Zimbabwe",
    "Marsa": "Malta",
    "Northwood": "England",
    "Dublin": "Ireland",
    "Colombo": "Sri Lanka",
    "Navi Mumbai": "India",
    "Kuala Lumpur": "Malaysia",
    "None": None,
    "Kuwait City": "Kuwait",
    "Bangi": "Malaysia",
    "Karachi": "Pakistan",
    "Murcia": "Spain",
    "Ilfov County": "Romania",
    "Rotterdam": "Netherlands",
    "London": "England",
    "Windhoek": "Namibia",
    "Mumbai": "India",
    "Brisbane": "Australia",
    "Schiedam": "Netherlands",
    "Birmingham": "England",
    "Leicester": "England",
    "Derby": "England",
    "Ahmedabad": "India",
    "Benoni": "South Africa",
    "Kolkata": "India",
    "Colwyn Bay": "Wales",
    "Cork": "Ireland",
    "Tarouba": "West Indies",  # Trinidad & Tobago
    "Bridgetown": "West Indies",  # Barbados
    "Bali": "Indonesia",
    "Incheon": "South Korea",
    "Barbados": "West Indies",
    "Krefeld": "Germany",
    "Lahore": "Pakistan",
    "Aberdeen": "Scotland",
    "The Hague": "Netherlands",
    "Amstelveen": "Netherlands",
    "Ayr": "Scotland",
    "Al Amarat": "Oman",
    "Pearland": "USA",
    "Chelmsford": "England",
    "Canterbury": "England",
    "Bristol": "England",
    "Bulawayo": "Zimbabwe",
    "Sharjah": "UAE",
    "Kandy": "Sri Lanka",
    "Southport": "England",
    "Southampton": "England",
    "Port Moresby": "Papua New Guinea",
    "Rawalpindi": "Pakistan",
    "Pune": "India",
    "Delhi": "India",
    "Port Soif": "Guernsey",
    "Utrecht": "Netherlands",
    "North Sound": "West Indies",  # Antigua
    "Chandigarh": "India",
    "Beckenham": "England",
    "Hamilton": "New Zealand",
    "Northampton": "England",
    "Bengaluru": "India",
    "Houston": "USA",
    "Nairobi": "Kenya",
    "Castel": "Guernsey",
    "Bangkok": "Thailand",
    "Dubai": "UAE",
    "Chester": "England",
    "Port Elizabeth": "South Africa",
    "Suva": "Fiji",
    "Lauderhill": "USA",
    "Nottingham": "England",
    "Basseterre": "West Indies",  # St Kitts & Nevis
    "Panama City": "Panama",
    "Cuttack": "India",
    "Chester-le-Street": "England",
    "Leeds": "England",
    "Blackpool": "England",
    "Arundel": "England",
    "Galle": "Sri Lanka",
    "Oakham": "England",
    "Dhaka": "Bangladesh",
    "Loughborough": "England",
    "Guildford": "England",
    "Kirtipur": "Nepal",
    "Guyana": "West Indies",
    "Edinburgh": "Scotland",
    "Kidderminster": "England",
    "Adelaide": "Australia",
    "Radlett": "England",
    "Kerava": "Finland",
    "Uxbridge": "England",
    "Ajman": "UAE",
    "Morrisville": "USA",
    "Sydney": "Australia",
    "Perth": "Australia",
    "Durban": "South Africa",
    "Geelong": "Australia",
    "Newport": "Wales",
    "St Clement": "Jersey",
    "Vantaa": "Finland",
    "St Kitts": "West Indies",
    "Kimberley": "South Africa",
    "Raipur": "India",
    "Potchefstroom": "South Africa",
    "Jamaica": "West Indies",
    "Liverpool": "England",
    "Mackay": "Australia",
    "Rajkot": "India",
    "Indore": "India",
    "Sano": "Japan",
    "Jaipur": "India",
    "Visakhapatnam": "India",
    "St Martin": "West Indies",  # French/Dutch Caribbean
    "Trinidad": "West Indies",  # Trinidad & Tobago
    "Christchurch": "New Zealand",
    "Auckland": "New Zealand",
    "Tunbridge Wells": "England",
    "Spinaceto": "Italy",
    "Mong Kok": "Hong Kong",
    "Centurion": "South Africa",
    "Kigali City": "Rwanda",
    "Sylhet": "Bangladesh",
    "Dreux": "France",
    "Sedbergh": "England",
    "Mount Maunganui": "New Zealand",
    "Kampala": "Uganda",
    "Gibraltar": "Gibraltar",
    "Buenos Aires": "Argentina",
    "Kingstown": "West Indies",  # St Vincent
    "St George's": "West Indies",  # Grenada
    "Johannesburg": "South Africa",
    "Rangiora": "New Zealand",
    "Abu Dhabi": "UAE",
    "Melbourne": "Australia",
    "Rome": "Italy",
    "Doha": "Qatar",
    "Accra": "Ghana",
    "Gros Islet": "West Indies",  # St Lucia
    "Hyderabad": "India",
    "Sofia": "Bulgaria",
    "Brondby": "Denmark",
    "Gqeberha": "South Africa",  # Formerly Port Elizabeth
    "Bangalore": "India",
    "Voorburg": "Netherlands",
    "Singapore": "Singapore",
    "St Saviour": "Jersey",
    "Grantham": "England",
    "Oslo": "Norway",
    "Kingston": "West Indies",  # Jamaica
    "Lower Austria": "Austria",
    "Rugby": "England",
    "Waringstown": "Northern Ireland",
    "Mirpur": "Bangladesh",
    "Wellington": "New Zealand",
    "Dallas": "USA",
    "Sookholme": "England",
    "Eglinton": "Northern Ireland",
    "Wollongong": "Australia",
    "Dundee": "Scotland",
    "Zagreb": "Croatia",
    "Padang": "Indonesia",
    "Cape Town": "South Africa",
    "Ghent": "Belgium",
    "Hobart": "Australia",
    "Coolidge": "West Indies",  # Antigua
    "Queenstown": "New Zealand",
    "Waterloo": "Belgium",
    "Dunedin": "New Zealand",
    "Providence": "West Indies",  # Guyana
    "Napier": "New Zealand",
    "Chattogram": "Bangladesh",
    "Abuja": "Nigeria",
    "Dambulla": "Sri Lanka",
    "Horsham": "England",
    "Gelephu": "Bhutan",
    "Gold Coast": "Australia",
    "Entebbe": "Uganda",
    "Lincoln": "England",
    "Apia": "Samoa",
    "Alexandra": "New Zealand",
    "Wong Nai Chung Gap": "Hong Kong",
    "Nagpur": "India",
    "Bloemfontein": "South Africa",
    "Paarl": "South Africa",
    "Noumea": "New Caledonia",
    "Los Angeles": "USA",
    "St Lucia": "West Indies",
    "Neath": "Wales",
    "Almeria": "Spain",
    "Dasmarinas": "Philippines",
    "Alice Springs": "Australia",
    "Nelson": "New Zealand",
    "Market Warsop": "England",
    "New York": "USA",
    "George Town": "West Indies",  # Cayman Islands
    "Dominica": "West Indies",
    "Ranchi": "India",
    "Londonderry": "Northern Ireland",
    "Sale": "England",
    "Newbury": "England",
    "Albury": "Australia",
    "New Chandigarh": "India",
    "Kanpur": "India",
    "Latschach": "Austria",
    "Guwahati": "India",
    "York": "England",
    "Zemst": "Belgium",
    "Cairns": "Australia",
    "Comber": "Northern Ireland",
    "Eastbourne": "England",
    "Belgrade": "Serbia",
    "Dharamsala": "India",
    "Koge": "Denmark",
    "Hove": "England",
    "Welbeck": "England",
    "Swansea": "Wales",
    "Port Vila": "Vanuatu",
    "Richmond": "England",
    "Bendigo": "Australia",
    "Canberra": "Australia",
    "Roseau": "West Indies",  # Dominica
    "Chiang Mai": "Thailand",
    "Lagos": "Nigeria",
    "Moe": "Australia",
    "Kathmandu": "Nepal",
    "Colchester": "England",
    "East London": "South Africa",
    "Vadodara": "India",
    "Deventer": "Netherlands",
    "Gosforth": "England",
    "Wicklow": "Ireland",
    "Port of Spain": "West Indies",  # Trinidad & Tobago
    "Wormsley": "England",
    "Carrara": "Australia",
    "Hangzhou": "China",
    "Kibworth": "England",
    "Thiruvananthapuram": "India",
    "Phnom Penh": "Cambodia",
    "Launceston": "Australia",
    "Palmerston North": "New Zealand",
    "Hong Kong": "Hong Kong",
    "Grenada": "West Indies",
    "Hambantota": "Sri Lanka",
    "New Plymouth": "New Zealand",
    "Chittagong": "Bangladesh",
    "Invercargill": "New Zealand",
    "Episkopi": "Cyprus",
    "Kwekwe": "Zimbabwe",
    "Whangarei": "New Zealand",
    "Antigua": "West Indies",
    "Naucalpan": "Mexico",
    "Corfu": "Greece",
    "Ballarat": "Australia",
    "Johor": "Malaysia",
    "Walferdange": "Luxembourg",
    "Solihull": "England",
    "Jinja": "Uganda",
    "Albergaria": "Portugal",
    "Kowloon": "Hong Kong",
    "Cox's Bazar": "Bangladesh",
    "Stirling": "Scotland",
    "Mohali": "India",
    "St Peter Port": "Guernsey",
    "Osaka": "Japan",
    "Townsville": "Australia",
    "Victoria": "Canada",
    "Blantyre": "Malawi",
    "Seropedica": "Brazil",
    "Khulna": "Bangladesh",
    "Kochi": "India",
    "Glasgow": "Scotland",
    "Gwalior": "India",
    "Milton Keynes": "England",
    "Pietermaritzburg": "South Africa",
    "Pallekele": "Sri Lanka",
    "Pokhara": "Nepal",
    "Dehra Dun": "India",
    "Latrobe": "Australia",
    "Arbroath": "Scotland",
    "Graz": "Austria",
    "Coffs Harbour": "Australia",
    "Frinton-on-Sea": "England",
    "Copenhagen": "Denmark",
    "Derry": "Northern Ireland",
    "Bowral": "Australia",
    "Street": "England",
    "Burnie": "Australia",
    "St Vincent": "West Indies",
    "Bermuda": "Bermuda",
    "Tallinn": "Estonia",
    "Mexico City": "Mexico",
    "Sind": "Pakistan",
    "Navile": "Italy",
    "FTZ Sports Complex": "Sri Lanka",
    "Milverton": "England",
    "Faridabad": "India",
    "Kolsva": "Sweden",
    "Bogra": "Bangladesh",
    "Pretoria": "South Africa",
    "Fatullah": "Bangladesh",
    "Coggeshall": "England",
    "Dharmasala": "India",
    "Faisalabad": "Pakistan",
    "St John's": "West Indies",  # Antigua
    "Margao": "India",
    "Nuriootpa": "Australia",
    "Bishop's Stortford": "England",
    "Medicina": "Italy",
    "Nettleworth": "England",
    "Pianoro": "Italy",
    "Surat": "India",
    "Bandar Kinrara": "Malaysia",
    "Kurunegala": "Sri Lanka",
    "Szodliget": "Hungary",
    "Strabane": "Northern Ireland",
    "Stockholm": "Sweden",
    "Darwin": "Australia",
    "Southend-on-Sea": "England",
    "Grand Prairie": "USA",
    "Halstead": "England",
    "Peshawar": "Pakistan",
    "Jamshedpur": "India",
    "Toronto": "Canada",
    "Katunayake": "Sri Lanka"
}

# for i in spark.sql("select distinct venue_name from all_matches where city is null and team_type='international'").collect():
#     print(i[0])

venue_to_country = {
    "Rangiri Dambulla International Stadium": "Sri Lanka",
    "Pallekele International Cricket Stadium": "Sri Lanka",
    "Dubai International Cricket Stadium": "UAE",
    "Harare Sports Club": "Zimbabwe",
    "Galle International Stadium": "Sri Lanka",
    "Adelaide Oval": "Australia",
    "Colombo Cricket Club Ground": "Sri Lanka",
    "Sano International Cricket Ground": "Japan",
    "Entebbe Cricket Oval": "Uganda",
    "Sydney Cricket Ground": "Australia",
    "Gahanga International Cricket Stadium": "Rwanda",
    "Perth Stadium": "Australia",
    "Al Amerat Cricket Ground Oman Cricket (Ministry Turf 1)": "Oman",
    "Al Amerat Cricket Ground Oman Cricket (Ministry Turf 2)": "Oman",
    "Melbourne Cricket Ground": "Australia",
    "Rawalpindi Cricket Stadium": "Pakistan",
    "San Albano": "Italy",
    "St Georges Quilmes": "Argentina",
    "Royal Chiangmai Golf Club": "Thailand",
    "Sir Vivian Richards Stadium, North Sound": "Antigua and Barbuda",
    "Sharjah Cricket Stadium": "UAE",
    "Chittagong Divisional Stadium": "Bangladesh",
    "Carrara Oval": "Australia",
    "Stellenbosch University 1": "South Africa",
    "Stellenbosch University 2": "South Africa",
    "Mombasa Sports Club Ground": "Kenya",
    "West Mersea Cricket Club": "England",
    "Bulawayo Athletic Club": "Zimbabwe",
    "Al Dhaid Cricket Village": "UAE",
    "Sylhet International Cricket Stadium": "Bangladesh",
    "Sylhet Stadium": "Bangladesh",
    "Multan Cricket Stadium": "Pakistan",
    "Tafawa Balewa Square (TBS) Cricket Oval": "Nigeria",
    "Queenstown Events Centre": "New Zealand",
    "Moara Vlasiei Cricket Ground": "Romania",
    "Dubai Sports City Cricket Stadium": "UAE",
    "Guanggong International Cricket Stadium": "China",
    "Hong Kong Cricket Club": "Hong Kong",
    "Johor Cricket Academy Oval": "Malaysia",
    "Louth Cricket Club": "England",
    "Sheikhupura Stadium": "Pakistan",
    "Arundel Castle Cricket Club Ground": "England"
}