from pyspark.sql.types import StructType, StructField, StringType, LongType

flattened_record_schema = StructType([
    StructField("innings_number",StringType(), True),
    StructField("batter_name",StringType(), True),
    StructField("batter_team",StringType(), True),
    StructField("batter_id",StringType(), True),
    StructField("bowler_name",StringType(), True),
    StructField("bowler_team",StringType(), True),
    StructField("bowler_id",StringType(), True),
    StructField("batter_runs",LongType(), True),
    StructField("extra_runs",LongType(), True),
    StructField("total_runs",LongType(), True),
    StructField("over",LongType(), True),
    StructField("ball",LongType(), True),
    StructField("is_wicket",LongType(), True),
    StructField("wicket_player_name",StringType(), True),
    StructField("wicket_player_id",StringType(), True),
    StructField("wicket_fielder_name",StringType(), True),
    StructField("wicket_fielder_id",StringType(), True),
    StructField("wicket_kind",StringType(), True),
    StructField("match_id",StringType(), True),
    StructField("start_date",StringType(), True),
    StructField("event_name",StringType(), True),
    StructField("match_type",StringType(), True),
    StructField("team_type",StringType(), True),
    StructField("venue_name",StringType(), True),
    StructField("city",StringType(), True),
    StructField("gender",StringType(), True),
    StructField("total_overs",LongType(), True),
    StructField("season",StringType(), True),
    StructField("toss",StringType(), True),
    StructField("team_1",StringType(), True),
    StructField("team_2",StringType(), True),
    StructField("year",LongType(), True),
    StructField("month",LongType(), True),
    StructField("dt",LongType(), True),
])